server:
  port: 8080
spring:
  application:
    name: micro-lending
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# DataSource configuration
datasource:
  jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  type: com.zaxxer.hikari.HikariDataSource
  username: sa
  password: sa

# Monitoring endpoints
management:
  endpoints.web.exposure.include: "info, health, metrics, configprops, env"
